# Generated by Django 5.1 on 2024-08-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoforum',
            name='thumb',
            field=models.ImageField(default='thumb_forum/default_thumb.jpg', upload_to='thumb_forum'),
        ),
    ]
