# Generated by Django 5.1 on 2024-08-29 03:14

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topicoforum_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicoforum',
            name='thumb',
            field=models.ImageField(default='thumb_forum/default_thumb.jpg', upload_to='thumb_forum', validators=[forum.models.validate_image]),
        ),
    ]
