# Generated by Django 5.1 on 2024-10-03 01:41

import forum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_topicoforum_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicoforum',
            name='thumb',
            field=models.ImageField(upload_to='thumb_forum', validators=[forum.models.validate_image]),
        ),
    ]
