# Generated by Django 5.1.2 on 2024-10-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0019_alter_aula_modulo'),
        ('forum', '0004_alter_topicoforum_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicoforum',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='curso.aula'),
            preserve_default=False,
        ),
    ]
