# Generated by Django 5.0.6 on 2024-07-02 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('thumb', models.ImageField(upload_to='thumb_cursos')),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('categoria1', 'Categoria 1'), ('categoria2', 'Categoria 2'), ('categoria3', 'Categoria 3')], max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('visualizacoes', models.IntegerField(default=0)),
            ],
        ),
    ]
