# Generated by Django 5.0.7 on 2024-07-17 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_usuario_cpf_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.BinaryField(),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(max_length=1000)),
                ('data_agendamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_doutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_doutor', to='curso.usuario')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to='curso.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LaudosMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.BinaryField()),
                ('observacao', models.TextField(max_length=1000)),
                ('data_inclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos_medicos', to='curso.usuario')),
            ],
        ),
    ]
