# Generated by Django 5.0.7 on 2024-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_rename_password_usuario_senha_alter_usuario_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laudosmedicos',
            name='documento',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='thumb_usuarios'),
        ),
    ]
