# Generated by Django 5.0.7 on 2024-07-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alter_laudosmedicos_documento_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('PR', 'Professor'), ('MD', 'Médico'), ('AL', 'Aluno')], default='AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
