# Generated by Django 5.0.7 on 2024-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_usuario_tipo_alter_usuario_data_de_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categorias',
            field=models.ManyToManyField(related_name='usuarios', to='curso.categorias'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descricao',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_plus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='web_site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
