# Generated by Django 5.1 on 2024-08-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_usuario_categorias_usuario_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='curso.categorias'),
        ),
    ]
