# Generated by Django 5.1 on 2024-08-16 00:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_alter_usuario_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id_remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laudosmedicos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos_medicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='id_doutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_doutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modulo_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badge',
            name='usuarios',
            field=models.ManyToManyField(related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='thumb_usuarios')),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_plus', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(blank=True, max_length=5000, null=True)),
                ('web_site', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo', models.CharField(choices=[('PR', 'Professor'), ('MD', 'Médico'), ('AL', 'Aluno')], default='AL', max_length=2)),
                ('categorias', models.ManyToManyField(blank=True, related_name='usuarios', to='curso.categorias')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
