# Generated by Django 5.1 on 2024-08-16 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_alter_chat_id_remetente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos.', regex='^\\d{11}$')]),
        ),
    ]
