# Generated by Django 5.1 on 2024-08-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_alter_userprofile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
