# Generated by Django 5.1 on 2024-08-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0014_curso_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='curso.userprofile'),
        ),
    ]
