# Generated by Django 5.1 on 2024-08-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0015_curso_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
