# Generated by Django 5.1 on 2024-09-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0018_alter_avaliacao_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='curso.modulo'),
        ),
    ]
