# Generated by Django 5.1 on 2024-10-18 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0020_progresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='curso.curso'),
        ),
    ]
