# Generated by Django 5.1 on 2024-10-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0021_alter_modulo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='emBreve',
            field=models.BooleanField(default=False),
        ),
    ]
