# Generated by Django 5.1 on 2024-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0022_curso_embreve'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aceito_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_declaracao_raca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='categoria_profissional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='especialidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grau_de_escolaridade',
            field=models.CharField(blank=True, choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ES', 'Ensino Superior'), ('PG', 'Pós-graduação')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ja_participou_capacitacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vinculado_instituicao',
            field=models.BooleanField(default=False),
        ),
    ]
