name: Django CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Verify Django Installation
      run: |
        source venv/bin/activate
        pip show django
        pip show djangorestframework

    - name: List Python Path
      run: |
        source venv/bin/activate
        python -c "import sys; print('\n'.join(sys.path))"

    - name: Run migrations
      run: |
        source venv/bin/activate
        python manage.py migrate

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Debug SSH Connection
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@89.117.32.80 'echo SSH connection successful'

    - name: Deploy to the server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@89.117.32.80 '
        echo "Starting deployment" &&
        cd /var/www/Instituto_backend &&
        echo "Configuring Git safe directory..." &&
        git config --global --add safe.directory /var/www/Instituto_backend &&
        echo "Updating repository..." &&
        git pull origin master &&
        echo "Current directory contents:" &&
        ls -la &&
        echo "Creating and activating virtual environment..." &&
        python3 -m venv venv &&
        source venv/bin/activate &&
        echo "Installing dependencies..." &&
        pip install -r requirements.txt &&
        echo "Running migrations..." &&
        python manage.py migrate &&
        echo "Collecting static files..." &&
        python manage.py collectstatic --noinput &&
        echo "Restarting Gunicorn..." &&
        systemctl restart gunicorn &&
        echo "Deployment completed"'
